todo/urls.py
from django.urls import path
from . import views
app_name = 'todo'

urlpatterns = [
    # Home
    path('', views.home, name='home_page'),
    # Auth
    path('signup/', views.signup_user.as_view(), name='signup_page'),
    path('logout/', views.logout_user.as_view(), name='logout_page'),
    path('login/', views.login_user.as_view(), name='login_page'),

    # Todos
    path('createtodo/', views.CreateTodo.as_view(), name='create_todo_page'),
    path('current/', views.current_todos.as_view(), name='current_page'),
    path('current/<int:todo_pk>/', views.TodoDetail.as_view(), name='todo_detail_page'),
    path('current/<int:todo_pk>/complete/', views.CompleteTodo.as_view(), name='complete_todo_page'),
    path('current/<int:todo_pk>/delete/', views.DeleteTodo.as_view(), name='delete_todo_page'),
    path('completed/', views.CompletedTodos.as_view(), name='completed_todos_page'),
]

todowoo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todo.urls')),
]

todo/models.py
from django.db import models
from django.contrib.auth.models import User

class Todo(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=128)
    memo = models.TextField(blank=True)

    created_at = models.DateTimeField(auto_now_add=True)        # not editable
    completed_at = models.DateTimeField(null=True, blank=True)  # not required
    important = models.BooleanField(default=False)

    def __str__(self):
        return self.title

todo/forms.py
from django.forms import ModelForm
from .models import Todo

class TodoForm(ModelForm):
    class Meta:
        model = Todo
        fields = ['title', 'memo', 'important']

todo/views.py
from django.views import View
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.models import User
from django.db import IntegrityError
from django.contrib.auth import login, logout, authenticate
from .forms import TodoForm
from .models import Todo
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

######################################################## Authenticate
class signup_user(View):
    def get(self, request):
        return render(request, 'todo/signupuser.html')
    
    def post(self, request):
        if request.POST.get('password1') == request.POST.get('password2'):
            try:
                username = request.POST.get('username')
                password = request.POST.get('password1')

                user = User.objects.create_user(username=username, password=password)
                login(request, user)

                return redirect('/createtodo/')
            except IntegrityError:

                return render(request, 'todo/signupuser.html', {'been_taken_error': 'That username had already been taken.'})

        else:
            return render(request, 'todo/signupuser.html', {'not_match_error': 'Passwords did not match.'})

class logout_user(View):
    @method_decorator(login_required)
    def post(self, request):
        logout(request)
        return redirect('/login/')


class login_user(View):
    def get(self, request):
        return render(request, 'todo/loginuser.html', {})

    def post(self, request):
        username = request.POST.get('username')
        password = request.POST.get('password')

        # authenticate, give a user object or None.
        user = authenticate(request, username=username, password=password)

        if user == None:
            return render(request, 'todo/loginuser.html', {'not_found_user_error': 'User not found.'})

        else:
            login(request, user)
            return redirect('/createtodo/')

########################################################

def home(request):
    return render(request, 'todo/home.html', {})

class current_todos(View):
    @method_decorator(login_required)
    def get(self, request):
        todos = Todo.objects.filter(user=request.user, completed_at__isnull=True).order_by('-created_at')
        return render(request, 'todo/currenttodos.html', {'todos': todos})
class CompletedTodos(View):
    @method_decorator(login_required)
    def get(self, request):
        todos = Todo.objects.filter(user=request.user, completed_at__isnull=False).order_by('-created_at')

        return render(request, 'todo/completed_todos.html', {'todos': todos})
class CreateTodo(View):
    @method_decorator(login_required)
    def get(self, request):
        return  render(request, 'todo/create_todo.html', {})

    @method_decorator(login_required)
    def post(self, request):
        # ??????????????????
        try:
            form = TodoForm(request.POST)
            new_todo = form.save(commit=False)
            new_todo.user = request.user
            new_todo.save()
        except ValueError:
            return  render(request, 'todo/create_todo.html', {'bad_date_error': 'Bad data passed in. Try again.'})

        # form.save()
        # return render(request, 'todo/create_todo.html', {'user': form.is_valid()})
        return redirect('/createtodo/')
class TodoDetail(View):
    @method_decorator(login_required)
    def get(self, request, todo_pk):
        todo = get_object_or_404(Todo, pk=todo_pk, user=request.user)
        
        return render(request, 'todo/todo_detail.html', {'todo': todo})
    @method_decorator(login_required)
    def post(self, request, todo_pk):
        todo = Todo.objects.get(pk=todo_pk)
        try:
            form = TodoForm(request.POST, instance=todo)
            form.save()
            # instead of the code down below, use the code up here.
            # if form.is_valid():
            #     todo.title = form.cleaned_data['title']
            #     todo.memo = form.cleaned_data['memo']
            #     todo.important = form.cleaned_data['important']
            #     todo.save()
                
        except ValueError:
            return  render(request, 'todo/todo_detail.html', {'todo': todo, 'bad_date_error': 'Bad data passed in. Try again.'})

        return redirect('/current/')
class CompleteTodo(View):
    @method_decorator(login_required)
    def post(self, request, todo_pk):
        todo = get_object_or_404(Todo, pk=todo_pk, user=request.user)
        todo.completed_at = timezone.now()
        todo.save()

        return redirect('/current/')
class DeleteTodo(View):
    @method_decorator(login_required)
    def post(self, request, todo_pk):
        todo = get_object_or_404(Todo, pk=todo_pk, user=request.user)
        todo.delete()

        return redirect('/current/')

todo/templates/todo/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TodoWoo</title>
    <link rel="stylesheet" href="{% static 'tailwind.css' %}">

</head>
<body>

    <nav class="bg-gray-800 py-2">
        <div class="text-center mb-2 sm:hidden">
          <a class="text-white font-semibold text-2xl" href="{% url 'todo:home_page' %}">TodoWoo</a>

        </div>

        <div class="text-center mb-2 sm:hidden">
            {% if user.is_authenticated %}
            <!-- Logged In as <span class="right-0 text-semibold"> {{user.username}}</span> -->
            <form action="{% url 'todo:logout_page' %}" method="POST">{% csrf_token %}
                <button class="text-gray-300 text-sm px-3 py-2 sm:hidden font-medium rounded-md hover:bg-gray-500 hover:text-white">Logout</button>
            </form>
            {% else %}
                <a class="text-gray-300 text-sm px-3 py-2 sm:hidden font-medium text-sm rounded-md hover:bg-gray-500 hover:text-white" href="{% url 'todo:login_page' %}">Login</a>
                <a class="text-gray-300 text-sm px-3 py-2 sm:hidden font-medium text-sm rounded-md hover:bg-gray-500 hover:text-white" href="{% url 'todo:signup_page' %}">Signup</a>
            {% endif %}

        </div>

        <div class="flex justify-center sm:justify-start max-w-7xl mx-auto py-2 px-6 sm:px-12 lg:px-8 sm:space-x-2 items-center">
                <a class="hidden sm:block text-white font-semibold text-2xl mr-6" href="{% url 'todo:home_page' %}">TodoWoo</a>
                <a class="bg-gray-900 mr-3 text-white px-3 py-2 rounded-md text-sm font-medium hover:bg-blue-800" href="{% url 'todo:current_page' %}">Current</a>
                <a class="bg-gray-900 mr-3 text-white px-3 py-2 rounded-md text-sm font-medium hover:bg-green-800" href="{% url 'todo:completed_todos_page' %}">Completed</a>
                <a class="bg-gray-900 text-white px-3 py-2 rounded-md text-sm font-medium hover:bg-purple-800" href="{% url 'todo:create_todo_page' %}">Create</a>

                {% if user.is_authenticated %}
                <!-- Logged In as <span class="right-0 text-semibold"> {{user.username}}</span> -->
                <form action="{% url 'todo:logout_page' %}" method="POST">{% csrf_token %}
                    <button class="text-gray-300 text-sm px-3 py-2 hidden sm:block font-medium rounded-md hover:bg-gray-500 hover:text-white">Logout</button>
                </form>
                {% else %}
                    <a class="text-gray-300 text-sm px-3 py-2 hidden sm:block font-medium text-sm rounded-md hover:bg-gray-500 hover:text-white" href="{% url 'todo:login_page' %}">Login</a>
                    <a class="text-gray-300 text-sm px-3 py-2 hidden sm:block font-medium text-sm rounded-md hover:bg-gray-500 hover:text-white" href="{% url 'todo:signup_page' %}">Signup</a>
                {% endif %}
            
    </nav>



    {% block content %}

    {% endblock %}
</body>
</html>

todo/templates/todo/completed_todos.html
{% extends 'todo/base.html' %}

{% block content %}
    <div class="min-h-screen flex justify-center py-10 px-4 sm:px-6 lg:px-8">
        <div class="max-w-md w-full ">
            <div class="text-blue-500 mb-12 text-center font-extrabold text-3xl">
                
                Completed Todos
            </div>
            
    {% for todo in todos %}
        <div class="justify-start px-4 sm:px-6 lg:px-8">
            <div class="flex flex-col mb-6 bg-green-100 px-4 py-4 rounded-md">
                <h1 class="text-green-600 text-xl mb-3 font-semibold">{{todo.title}}</h1>
                <p class="text-green-500 break-all mb-4">{{todo.memo}}</p>
                <p class="text-green-500 text-xs">completed at: {{todo.completed_at|date:'M j Y H:i'}}</p>
            </div>
            
        </div>
    {% endfor %}

    </div>

{% endblock %}

todo/templates/todo/create_todo.html
{% extends 'todo/base.html' %}

{% block content %}


<div class="min-h-screen flex justify-center py-12 px-4 sm:px-6 lg:px-8">
  <div class="max-w-md w-full space-y-8">

    <div class="text-blue-600 text-center font-extrabold text-3xl">

      Create Todo
    </div>
    <p class="text-red-500 text-center font-semibold">{{bad_date_error}}</p>


      
      <form class="mt-8 space-y-6" action="#" method="POST">{% csrf_token %}
          <div class="rounded-md shadow-sm -space-y-px">
            <div>
              <input id="id_title" name="title" type="text" maxlength="128" required class="rounded-md mb-6 relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm" placeholder="Title">
              <textarea id="id_memo" name="memo" rows="5" class="bg-gray-100 px-3 py-2 mb-6 border border-solid placeholder-gray-500 rounded-md text-gray-900 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 w-full" placeholder="Memo"></textarea>

              <div class="flex-col mb-6 space-x-1">
                  <input id="id_important" type="checkbox" name="important" class="checked:bg-blue-600 checked:border-transparent my-auto">
                  <label for="id_important" class="text">important</label>

              </div>
            </div>
            
      
            <button type="submit" class="group relative w-1/2 mx-auto flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                <span class="absolute left-0 inset-y-0 flex items-center pl-3">
                </span>
                Create
            </button>
      </form>

      </div>
</div>



{% endblock %}

todo/templates/todo/currenttodos.html
{% extends 'todo/base.html' %}

{% block content %}
    {% if todos.count == 0 %}
        <div class="min-h-screen flex justify-center py-12 px-4 sm:px-6 lg:px-8">
            <div class="flex flex-col max-w-2xl w-full space-y-6 text-center">
                <h1 class="text-3xl font-semibold text-gray-800">Looks like you don't have any todos! Nice work.</h1>
                <a href="{% url 'todo:create_todo_page' %}" class="text-white w-24 mx-auto bg-indigo-600 py-2 px-4 rounded rounded-md font-semibold hover:bg-indigo-800 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-600">Create</a>
    
            </div>
          </div>
    
    {% else %}
        <div class="min-h-screen flex justify-center py-10 px-4 sm:px-6 lg:px-8">
            <div class="max-w-md w-full ">
                <div class="text-blue-500 mb-12 text-center font-extrabold text-3xl">
                    
                    Current Todos
                </div>

                
                {% for todo in todos %}
                <div class="justify-start  px-4 sm:px-6 lg:px-8">
                    
                    {% if todo.important %}
                    <a href="{% url 'todo:todo_detail_page' todo.id %}">
                        <div class="group flex flex-col mb-6 bg-yellow-100 px-4 py-4 rounded-md hover:bg-yellow-50">
                            <h1 class="text-yellow-600 text-xl mb-3 font-semibold">{{todo.title}}</h1>
                            <p class="text-yellow-500 break-all mb-4">{{todo.memo}}</p>
                            <p class="text-yellow-500 text-xs mb-4">created at: {{todo.created_at|date:'M j Y H:i'}}</p>
                            
                            <form action="{% url 'todo:complete_todo_page' todo.id %}" method="POST" class="text-center">{% csrf_token %}
                                <button class="bg-yellow-600 w-min mx-auto px-3 py-2 rounded-md text-white font-semibold hover:bg-yellow-900">Done</button>
                            </form>
                        </div>
                    </a>
                    {% else %}
                    <a href="{% url 'todo:todo_detail_page' todo.id %}">
                        <div class="flex flex-col mb-6 bg-blue-100 px-4 py-4 rounded-md hover:bg-blue-50">
                            <h1 class="text-blue-600 text-xl mb-3 font-semibold">{{todo.title}}</h1>
                            <p class="text-blue-500 break-all mb-4">{{todo.memo}}</p>
                            <p class="text-blue-500 text-xs mb-4">created at: {{todo.created_at|date:'M j Y H:i'}}</p>
                            
                            <form action="{% url 'todo:complete_todo_page' todo.id %}" method="POST" class="text-center">{% csrf_token %}
                                <button class="bg-blue-600 w-min mx-auto px-3 py-2 rounded-md text-white font-semibold hover:bg-blue-900">Done</button>
                            </form>
                        </div>
                    </a>
                    
                    {% endif %}
                    
                </div>
                {% endfor %}
                
            </div>
    {% endif %}

{% endblock %}

todo/templates/todo/home.html
{% extends 'todo/base.html' %}

{% block content %}

    <div class="min-h-screen flex justify-center py-12 px-4 sm:px-6 lg:px-8">
        <div class="flex flex-col max-w-2xl w-full space-y-6 text-center">
            <h1 class="text-3xl font-semibold text-gray-800">Simply Your Todos. Woo!</h1>
            <p class="text-gray-900 text-md">Life is fun, But life is also busy, There's a million different things you could be doing. But what matters is what you do. We created<span class="font-bold italic"> TodoWoo </span>to help you make sense of all of your opportunities and live that life that matters most to you. Your new organized life awaits.</p>
            <a href="{% url 'todo:create_todo_page' %}" class="text-white w-24 mx-auto bg-indigo-600 py-2 px-4 rounded rounded-md font-semibold hover:bg-indigo-800 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-600">Start</a>
        </div>
      </div>

{% endblock %}

todo/templates/todo/loginuser.html
{% extends 'todo/base.html' %}

{% block content %}

    <div class="min-h-screen flex justify-center py-12 px-4 sm:px-6 lg:px-8">
        <div class="max-w-md w-full space-y-8">
            <h2 class="mt-6 text-center text-3xl font-extrabold text-indigo-800">
              Login
            </h2>

            <p class="text-red-500 text-center font-semibold">{{not_found_user_error}}</p>

          <form class="mt-8 space-y-6" action="{% url 'todo:login_page' %}" method="POST">{% csrf_token %}
            <div class="rounded-md shadow-sm -space-y-px">
              <div>
                <input id="id_username" name="username" type="text" required class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm" placeholder="Username">
              </div>
              <div>
                <input id="id_password" name="password" type="password" autocomplete="current-password" required class="appearance-none rounded-none rounded-b-md relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm" placeholder="Password">
              </div>
            </div>
      
      
            <button type="submit" class="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                <span class="absolute left-0 inset-y-0 flex items-center pl-3">
                    <!-- Heroicon name: solid/lock-closed -->
                    <svg class="h-5 w-5 text-indigo-500 group-hover:text-indigo-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                    <path fill-rule="evenodd" d="M5 9V7a5 5 0 0110 0v2a2 2 0 012 2v5a2 2 0 01-2 2H5a2 2 0 01-2-2v-5a2 2 0 012-2zm8-2v2H7V7a3 3 0 016 0z" clip-rule="evenodd" />
                    </svg>
                </span>
                Login
            </button>
            <p class="text-gray-600 text-sm text-center">Need an account? <a href="{% url 'todo:signup_page' %}" class="text-indigo-800 font-semibold">Sign Up</a></p>
          </form>
        </div>
      </div>


{% endblock %}

todo/templates/todo/signupuser.html
{% extends 'todo/base.html' %}

{% block content %}

    <div class="min-h-screen flex justify-center py-12 px-4 sm:px-6 lg:px-8">
        <div class="max-w-md w-full space-y-8">
            <h2 class="mt-6 text-center text-3xl font-extrabold text-indigo-800">
              Sign Up
            </h2>

            <p class="text-red-500 text-center font-semibold">{{not_match_error}}</p>
            <p class="text-red-500 text-center font-semibold">{{been_taken_error}}</p>

          <form class="mt-8 space-y-6" action="#" method="POST">{% csrf_token %}
            <div class="rounded-md shadow-sm -space-y-px">
              <div>
                <input id="id_username" name="username" type="text" required class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm" placeholder="Username">
              </div>
              <div>
                <input id="id_password1" name="password1" type="password" autocomplete="current-password" required class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm" placeholder="Password">
              </div>
              <div>
                <input id="id_password2" name="password2" type="password" autocomplete="current-password" required class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-b-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm" placeholder="Confirm Password">
              </div>
            </div>
      
      
            <button type="submit" class="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                <span class="absolute left-0 inset-y-0 flex items-center pl-3">
                    <!-- Heroicon name: solid/lock-closed -->
                    <svg class="h-5 w-5 text-indigo-500 group-hover:text-indigo-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                    <path fill-rule="evenodd" d="M5 9V7a5 5 0 0110 0v2a2 2 0 012 2v5a2 2 0 01-2 2H5a2 2 0 01-2-2v-5a2 2 0 012-2zm8-2v2H7V7a3 3 0 016 0z" clip-rule="evenodd" />
                    </svg>
                </span>
                Sign Up
            </button>

            <p class="text-gray-600 text-sm text-center">Do you already have an account? <a href="{% url 'todo:login_page' %}" class="text-indigo-800 font-semibold">Login here</a></p>
            
          </form>
        </div>
      </div>


{% endblock %}

todo/templates/todo/todo_detail.html
{% extends 'todo/base.html' %}

{% block content %}


<div class="min-h-screen flex justify-center py-12 px-4 sm:px-6 lg:px-8">
  <div class="max-w-md w-full space-y-8">

    <p class="text-red-500 text-center font-semibold">{{bad_date_error}}</p>


      
      <form class="mt-8 space-y-6" action="#" method="POST">{% csrf_token %}
          <div class="rounded-md shadow-sm -space-y-px">
            <div>
              <input id="id_title" name="title" type="text" maxlength="128" required class="rounded-md mb-6 relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm" placeholder="Title" value="{{todo.title}}">
              <textarea id="id_memo" name="memo" rows="5" class="bg-gray-100 px-3 py-2 mb-6 border border-solid placeholder-gray-500 rounded-md text-gray-900 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 w-full" placeholder="Memo">{{todo.memo}}</textarea>
              <div class="flex-col mb-6 space-x-1">
                  {% if todo.important %}
                    <input id="id_important" type="checkbox" name="important" checked class="checked:bg-blue-600 checked:border-transparent my-auto">
                    <label for="id_important" class="text">important</label>
                    {% else %}
                    <input id="id_important" type="checkbox" name="important" class="checked:bg-blue-600 checked:border-transparent my-auto">
                    <label for="id_important" class="text">important</label>
                  {% endif %}

              </div>
            </div>
            
      
            <button type="submit" class="group mb-6 relative w-1/2 mx-auto flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                <span class="absolute left-0 inset-y-0 flex items-center pl-3">
                </span>
                Update
            </button>
      </form>

      <form action="{% url 'todo:delete_todo_page' todo.id %}" method="POST">{% csrf_token %}
          <button type="submit" class="mt-4 group relative w-1/2 mx-auto flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-red-600 hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500">
            <span class="absolute left-0 inset-y-0 flex items-center pl-3">
            </span>
            Delete
        </button>

      </form>



      </div>
</div>



{% endblock %}